-- ===================================================================
-- AI SHIELD DATABASE SCHEMA INITIALIZATION (V1)
-- Enterprise-grade DDL for PostgreSQL and ANSI-SQL compatible RDBMS
-- ===================================================================

-- 1. USERS TABLE
CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(50) NOT NULL,
    phone VARCHAR(50),
    mobile_verified BOOLEAN NOT NULL DEFAULT FALSE,
    mobile_verified_at TIMESTAMP,
    location VARCHAR(255),
    bio VARCHAR(1000),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 2. CARDS TABLE
CREATE TABLE IF NOT EXISTS cards (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    card_number_masked VARCHAR(255) NOT NULL,
    card_last4 VARCHAR(10) NOT NULL,
    card_type VARCHAR(50),
    status VARCHAR(50) NOT NULL,
    daily_limit DOUBLE PRECISION DEFAULT 100000.0,
    monthly_limit DOUBLE PRECISION DEFAULT 500000.0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_cards_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_cards_user_id ON cards(user_id);
CREATE INDEX IF NOT EXISTS idx_cards_last4 ON cards(card_last4);

-- 3. TRANSACTIONS TABLE
CREATE TABLE IF NOT EXISTS transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_ref VARCHAR(64) NOT NULL UNIQUE,
    user_id BIGINT,
    card_id BIGINT,
    customer_name VARCHAR(255) NOT NULL,
    card_masked VARCHAR(64) NOT NULL,
    amount DOUBLE PRECISION NOT NULL,
    currency VARCHAR(10) DEFAULT 'INR',
    merchant_name VARCHAR(255),
    merchant_category VARCHAR(100),
    location VARCHAR(255) NOT NULL,
    device_fingerprint VARCHAR(255),
    ip_address VARCHAR(100),
    timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    status VARCHAR(50) NOT NULL,
    risk VARCHAR(50) NOT NULL,
    risk_score INTEGER NOT NULL,
    decision_reasons VARCHAR(2000),
    decision VARCHAR(50),
    ml_probability DOUBLE PRECISION,
    rule_score DOUBLE PRECISION,
    ml_score DOUBLE PRECISION,
    CONSTRAINT fk_transactions_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_transactions_card FOREIGN KEY (card_id) REFERENCES cards(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_tx_ref ON transactions(transaction_ref);
CREATE INDEX IF NOT EXISTS idx_tx_user ON transactions(user_id);
CREATE INDEX IF NOT EXISTS idx_tx_card ON transactions(card_id);
CREATE INDEX IF NOT EXISTS idx_tx_timestamp ON transactions(timestamp);

-- 4. FRAUD ALERTS TABLE
CREATE TABLE IF NOT EXISTS fraud_alerts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    alert_ref VARCHAR(64) NOT NULL UNIQUE,
    transaction_id BIGINT,
    transaction_ref VARCHAR(64),
    customer_name VARCHAR(255) NOT NULL,
    amount DOUBLE PRECISION NOT NULL,
    risk_score INTEGER NOT NULL,
    location VARCHAR(255) NOT NULL,
    status VARCHAR(50) NOT NULL,
    trigger_reasons VARCHAR(2000),
    assigned_investigator VARCHAR(255),
    investigator_notes VARCHAR(2000),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    resolved_at TIMESTAMP,
    CONSTRAINT fk_alerts_tx FOREIGN KEY (transaction_id) REFERENCES transactions(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_alert_ref ON fraud_alerts(alert_ref);
CREATE INDEX IF NOT EXISTS idx_alert_tx_ref ON fraud_alerts(transaction_ref);
CREATE INDEX IF NOT EXISTS idx_alert_status ON fraud_alerts(status);

-- 5. FRAUD AUDIT LOGS TABLE (IMMUTABLE AUDIT TRAIL)
CREATE TABLE IF NOT EXISTS fraud_audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    event_type VARCHAR(64) NOT NULL,
    transaction_ref VARCHAR(64),
    card_last4 VARCHAR(10),
    user_id BIGINT,
    customer_name VARCHAR(255),
    action_taken VARCHAR(100),
    risk_score INTEGER,
    ml_probability DOUBLE PRECISION,
    triggered_rules VARCHAR(2048),
    client_ip VARCHAR(100),
    user_agent VARCHAR(500),
    details VARCHAR(2048)
);

CREATE INDEX IF NOT EXISTS idx_audit_tx_ref ON fraud_audit_logs(transaction_ref);
CREATE INDEX IF NOT EXISTS idx_audit_event_type ON fraud_audit_logs(event_type);
CREATE INDEX IF NOT EXISTS idx_audit_timestamp ON fraud_audit_logs(timestamp);

-- 6. FRAUD RULES TABLE (DYNAMIC WEIGHTS & POLICY TOGGLES)
CREATE TABLE IF NOT EXISTS fraud_rules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rule_key VARCHAR(64) NOT NULL UNIQUE,
    rule_name VARCHAR(255) NOT NULL,
    description VARCHAR(1000),
    category VARCHAR(50) NOT NULL,
    weight DOUBLE PRECISION NOT NULL DEFAULT 1.0,
    threshold_value DOUBLE PRECISION NOT NULL DEFAULT 0.0,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_rules_key ON fraud_rules(rule_key);

-- 7. NOTIFICATION LOGS TABLE
CREATE TABLE IF NOT EXISTS notification_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT,
    transaction_id BIGINT,
    destination VARCHAR(100) NOT NULL,
    notification_type VARCHAR(64) NOT NULL,
    status VARCHAR(50) NOT NULL,
    provider_name VARCHAR(50),
    provider_reference VARCHAR(255),
    failure_reason VARCHAR(1000),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    sent_at TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_notif_status ON notification_logs(status);
CREATE INDEX IF NOT EXISTS idx_notif_user_id ON notification_logs(user_id);
CREATE INDEX IF NOT EXISTS idx_notif_tx_id ON notification_logs(transaction_id);

-- 8. OTP VERIFICATIONS TABLE
CREATE TABLE IF NOT EXISTS otp_verifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT,
    destination VARCHAR(100) NOT NULL,
    challenge_id VARCHAR(64) UNIQUE,
    purpose VARCHAR(50) DEFAULT 'LOGIN',
    otp_hash VARCHAR(255) NOT NULL,
    status VARCHAR(50) NOT NULL DEFAULT 'PENDING',
    attempts INTEGER NOT NULL DEFAULT 0,
    max_attempts INTEGER NOT NULL DEFAULT 5,
    expires_at TIMESTAMP NOT NULL,
    resend_cooldown_until TIMESTAMP,
    verified_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_otp_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_otp_destination ON otp_verifications(destination);
CREATE INDEX IF NOT EXISTS idx_otp_status ON otp_verifications(status);
CREATE INDEX IF NOT EXISTS idx_otp_user_id ON otp_verifications(user_id);

-- 9. SYSTEM SETTINGS TABLE
CREATE TABLE IF NOT EXISTS system_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dark_mode BOOLEAN NOT NULL DEFAULT FALSE,
    notifications BOOLEAN NOT NULL DEFAULT TRUE,
    ai_detection BOOLEAN NOT NULL DEFAULT TRUE,
    auto_block BOOLEAN NOT NULL DEFAULT FALSE,
    threshold INTEGER NOT NULL DEFAULT 80,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 10. TRANSACTION VERIFICATIONS TABLE (STEP-UP CHALLENGES)
CREATE TABLE IF NOT EXISTS transaction_verifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    verification_request_id VARCHAR(64) NOT NULL UNIQUE,
    transaction_id BIGINT NOT NULL,
    transaction_ref VARCHAR(64) NOT NULL,
    user_id BIGINT,
    customer_email VARCHAR(255) NOT NULL,
    customer_name VARCHAR(255) NOT NULL,
    customer_phone VARCHAR(50),
    card_masked VARCHAR(64) NOT NULL,
    amount DOUBLE PRECISION NOT NULL,
    merchant_name VARCHAR(255),
    location VARCHAR(255),
    risk_level VARCHAR(50),
    risk_score INTEGER,
    status VARCHAR(50) NOT NULL,
    sms_status VARCHAR(50),
    sms_content VARCHAR(1000),
    requested_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMP NOT NULL,
    verified_at TIMESTAMP,
    verification_method VARCHAR(50),
    challenge_token VARCHAR(128) NOT NULL,
    security_metadata VARCHAR(2000),
    failure_reason VARCHAR(1000),
    audit_notes VARCHAR(2000),
    CONSTRAINT fk_verif_tx FOREIGN KEY (transaction_id) REFERENCES transactions(id) ON DELETE CASCADE,
    CONSTRAINT fk_verif_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_verif_req_id ON transaction_verifications(verification_request_id);
CREATE INDEX IF NOT EXISTS idx_verif_status ON transaction_verifications(status);
CREATE INDEX IF NOT EXISTS idx_verif_customer_email ON transaction_verifications(customer_email);

-- 11. TRAVEL NOTICES TABLE (CARDHOLDER TRAVEL MODE)
CREATE TABLE IF NOT EXISTS travel_notices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT,
    customer_email VARCHAR(255) NOT NULL,
    card_masked VARCHAR(64) NOT NULL,
    destination_country VARCHAR(100) NOT NULL,
    destination_city VARCHAR(100) NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    status VARCHAR(50) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_travel_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_travel_email ON travel_notices(customer_email);
CREATE INDEX IF NOT EXISTS idx_travel_status ON travel_notices(status);
